// src/views/Privacy.vue
<template>
    <div class="main-container">
        <div class="privacy-content main-content">
            <section>
                <h1>Datenschutzerklärung</h1>

                <p>
                    Dies ist keine kommerzielle Website. Wir sie lediglich für private und universitäre
                    Forschungszwecke im Rahmen einer Promotion im Bereich Mensch-Maschine Interaktion.
                </p>

                <p>
                    Personenbezogene Daten (nachfolgend zumeist nur „Daten“ genannt) werden von uns nur im Rahmen der
                    Erforderlichkeit sowie zum Zwecke der Bereitstellung eines funktionsfähigen und nutzerfreundlichen
                    Internetauftritts, inklusive seiner Inhalte und der dort angebotenen Leistungen, verarbeitet.
                </p>

                <p>
                    Gemäß Art. 4 Ziffer 1. der Verordnung (EU) 2016/679, also der Datenschutz-Grundverordnung
                    (nachfolgend nur „DSGVO“ genannt), gilt als „Verarbeitung“ jeder mit oder ohne Hilfe automatisierter
                    Verfahren ausgeführter Vorgang oder jede solche Vorgangsreihe im Zusammenhang mit personenbezogenen
                    Daten, wie das Erheben, das Erfassen, die Organisation, das Ordnen, die Speicherung, die Anpassung
                    oder Veränderung, das Auslesen, das Abfragen, die Verwendung, die Offenlegung durch übermittlung,
                    Verbreitung oder eine andere Form der Bereitstellung, den Abgleich oder die Verknüpfung, die
                    Einschränkung, das Löschen oder die Vernichtung.
                </p>
                <p>
                    Mit der nachfolgenden Datenschutzerklärung informieren wir Sie insbesondere über Art, Umfang, Zweck,
                    Dauer und Rechtsgrundlage der Verarbeitung personenbezogener Daten, soweit wir entweder allein oder
                    gemeinsam mit anderen über die Zwecke und Mittel der Verarbeitung entscheiden. Zudem informieren wir
                    Sie nachfolgend über die von uns zu Optimierungszwecken sowie zur Steigerung der Nutzungsqualität
                    eingesetzten Fremdkomponenten, soweit hierdurch Dritte Daten in wiederum eigener Verantwortung
                    verarbeiten.
                </p>
                <p>
                    Unsere Datenschutzerklärung ist wie folgt gegliedert:
                    <br/>
                    I. Informationen über uns als Verantwortliche
                    <br/>
                    II. Rechte der Nutzer und Betroffenen
                    <br/>
                    III. Informationen zur Datenverarbeitung
                </p>
            </section>

            <section>
                <h2>I. Informationen über uns als Verantwortliche</h2>
                <p>Verantwortlicher Anbieter und Datenschutzbeauftragter dieses Internetauftritts im
                    datenschutzrechtlichen Sinne ist:
                </p>
                <p>
                    {{name}}<br/>
                    {{street}}<br/>
                    {{address}}<br/>
                    {{country}}<br/>

                    {{phone}}<br/>
                    <a class="link" v-bind:href="'mailto:'+email">{{email}}</a>
                </p>
            </section>

            <section>
                 <h2>II. Rechte der Nutzer und Betroffenen</h2>
                <p>Mit Blick auf die nachfolgend noch näher beschriebene Datenverarbeitung haben die Nutzer und
                    Betroffenen folgende Rechte.
                </p>
                <ul>
                    <li>Recht auf Bestätigung, ob sie betreffende Daten verarbeitet werden, auf Auskunft über die
                        verarbeiteten Daten, auf weitere Informationen über die Datenverarbeitung sowie auf Kopien der
                        Daten (vgl. auch Art. 15 DSGVO).
                    </li>
                    <li>Recht auf Berichtigung oder Vervollständigung unrichtiger bzw. unvollständiger Daten (vgl. auch
                        Art. 16 DSGVO).
                    </li>
                    <li>Recht auf unverzügliche Löschung der sie betreffenden Daten (vgl. auch Art. 17 DSGVO), oder,
                        alternativ, soweit eine weitere Verarbeitung gemäß Art. 17 Abs. 3 DSGVO erforderlich ist, auf
                        Einschränkung der Verarbeitung nach Maßgabe von Art. 18 DSGVO.
                    </li>
                    <li>Recht auf Erhalt der sie betreffenden und von ihnen bereitgestellten Daten und auf übermittlung
                        dieser Daten an andere Anbieter/Verantwortliche (vgl. auch Art. 20 DSGVO).
                    </li>
                    <li>Recht auf Beschwerde gegenüber der Aufsichtsbehörde, sofern sie der Ansicht sind, dass die sie
                        betreffenden Daten durch den Anbieter unter Verstoß gegen datenschutzrechtliche Bestimmungen
                        verarbeitet werden (vgl. auch Art. 77 DSGVO).
                    </li>
                </ul>
                <p>Darüber hinaus ist der Anbieter dazu verpflichtet, alle Empfänger, denen gegenüber Daten durch den
                    Anbieter offengelegt worden sind, über jedwede Berichtigung oder Löschung von Daten oder die
                    Einschränkung der Verarbeitung, die aufgrund der Artikel 16, 17 Abs. 1, 18 DSGVO erfolgt, zu
                    unterrichten. Diese Verpflichtung besteht jedoch nicht, soweit diese Mitteilung unmöglich oder mit
                    einem unverhältnismäßigen Aufwand verbunden ist. Unbeschadet dessen hat der Nutzer ein Recht auf
                    Auskunft über diese Empfänger.
                </p>
                <p>Ebenfalls haben die Nutzer und Betroffenen nach Art. 21 DSGVO das Recht auf Widerspruch gegen die
                    künftige Verarbeitung der sie betreffenden Daten, sofern die Daten durch den Anbieter nach Maßgabe
                    von Art. 6 Abs. 1 lit. f) DSGVO verarbeitet werden. Insbesondere ist ein Widerspruch gegen die
                    Datenverarbeitung zum Zwecke der Direktwerbung statthaft.</p>
            </section>

            <section>
               <h2>III Informationen zur Datenverarbeitung</h2>
                <p>Ihre bei Nutzung unseres Internetauftritts verarbeiteten Daten werden gelöscht oder gesperrt, sobald
                    der Zweck der Speicherung entfällt, der Löschung der Daten keine gesetzlichen Aufbewahrungspflichten
                    entgegenstehen und nachfolgend keine anderslautenden Angaben zu einzelnen Verarbeitungsverfahren
                    gemacht werden.
                </p>
                <h3>Serverdaten</h3>
                <p>Aus technischen Gründen, insbesondere zur Gewährleistung eines sicheren und stabilen
                    Internetauftritts, werden Daten durch Ihren Internet-Browser an uns bzw. an unseren
                    Webspace-Provider übermittelt. Mit diesen sog. Server-Logfiles werden u.a. Typ und Version Ihres
                    Internetbrowsers, das Betriebssystem, die Website, von der aus Sie auf unseren Internetauftritt
                    gewechselt haben (Referrer URL), die Website(s) unseres Internetauftritts, die Sie besuchen, Datum
                    und Uhrzeit des jeweiligen Zugriffs sowie die IP-Adresse des Internetanschlusses, von dem aus die
                    Nutzung unseres Internetauftritts erfolgt, erhoben.</p>
                <p>Diese so erhobenen Daten werden vorrübergehend gespeichert, dies jedoch nicht gemeinsam mit anderen Daten von Ihnen.</p>
                <p>Diese Speicherung erfolgt auf der Rechtsgrundlage von Art. 6 Abs. 1 lit. f) DSGVO. Unser berechtigtes Interesse liegt in der Verbesserung, Stabilität, Funktionalität und Sicherheit unseres Internetauftritts.</p>
            <p>Die Daten werden spätestens nach sieben Tage wieder gelöscht, soweit keine weitere Aufbewahrung zu Beweiszwecken erforderlich ist. Andernfalls sind die Daten bis zur endgültigen Klärung eines Vorfalls ganz oder teilweise von der Löschung ausgenommen.</p>
                <p>Diese Datenschutzerklärung basiert auf der Muster-Datenschutzerklärung der <a target="_blank" class="link" href="https://www.ratgeberrecht.eu/">Anwaltskanzlei Weiß & Partner</a></p>
            </section>
        </div>

        <Footer></Footer>
    </div>
</template>

<script lang="ts">
import { Options, Vue } from "vue-class-component";
import Footer from "@/components/Footer.vue"; // @ is an alias to /src

@Options({
    components: {
        Footer,
    },
})
export default class Privacy extends Vue {

    data() {
        return {
            name: 'Matthias Schmidmaier',
            street: 'Karlstr. 120',
            address: '80335 München',
            country: 'Germany',
            email: 'matthias.schmidmaier@ifi.lmu.de',
            phone: '+49 (89) 26018735'
        }
    }
}
</script>

<style lang="scss" scoped>
    @import "@/scss/_styles.scss";

    .privacy-content {
        display: flex;
        flex-direction: column;
        justify-content: start;
        align-items: start;
        row-gap: 20px;
    }

    section {
        max-width: $max-content-width;
        text-align: left;
        display: flex;
        flex-direction: column;
        justify-content: start;
        align-items: start;
        text-align: left;

        h2 {
            text-align: left;
            margin: 0 0 5px 0;
        }

        p {
            text-align: justify;
            margin: 0 0 15px 0;
            font-size: $font-size-small;
        }

        ul {
            font-size: $font-size-small;
            padding-left: 20px;
        }

        li {
            padding-bottom: 5px;
        }

        .link {
            color: inherit;
            text-decoration: underline;
        }
    }

</style>

// c9/src/app/components/privacy/privacy.component.ts
import { Component, OnInit } from '@angular/core';
import {DataService} from '../../services/data/data.service';

@Component({
  selector: 'app-privacy',
  templateUrl: './privacy.component.html',
  styleUrls: ['./privacy.component.scss']
})
export class PrivacyComponent implements OnInit {

  mllink = '';
  mlurl = '';
  phn = '';
  owner = '';
  city = '';
  street = '';

  constructor(private data: DataService) {}

  ngOnInit() {
    this.mllink = this.data.mllink;
    this.mlurl = this.data.mlurl;
    this.phn = this.data.phone;
    this.owner = this.data.owner;
    this.city = this.data.city;
    this.street = this.data.street;
  }

}

<div class="mat-body">

  <h1>Datenschutzerklärung</h1>
  <p>Dies ist keine kommerzielle Website. Wir nutzen chapek9.org lediglich f&uuml;r private und
    universit&auml;re Forschungszwecke im Rahmen einer Promotion im Bereich Mensch-Maschine Interaktion.
  </p>
  <p>Personenbezogene Daten (nachfolgend zumeist nur „Daten“ genannt) werden von uns nur im Rahmen der Erforderlichkeit sowie zum Zwecke der Bereitstellung eines funktionsf&auml;higen und nutzerfreundlichen Internetauftritts, inklusive seiner Inhalte und der dort angebotenen Leistungen, verarbeitet.</p>
  <p>Gem&auml;ß Art. 4 Ziffer 1. der Verordnung (EU) 2016/679, also der Datenschutz-Grundverordnung (nachfolgend nur „DSGVO“ genannt), gilt als „Verarbeitung“ jeder mit oder ohne Hilfe automatisierter Verfahren ausgef&uuml;hrter Vorgang oder jede solche Vorgangsreihe im Zusammenhang mit personenbezogenen Daten, wie das Erheben, das Erfassen, die Organisation, das Ordnen, die Speicherung, die Anpassung oder Ver&auml;nderung, das Auslesen, das Abfragen, die Verwendung, die Offenlegung durch &uuml;bermittlung, Verbreitung oder eine andere Form der Bereitstellung, den Abgleich oder die Verkn&uuml;pfung, die Einschr&auml;nkung, das L&ouml;schen oder die Vernichtung.</p>
  <p>Mit der nachfolgenden Datenschutzerkl&auml;rung informieren wir Sie insbesondere &uuml;ber Art, Umfang, Zweck, Dauer und Rechtsgrundlage der Verarbeitung personenbezogener Daten, soweit wir entweder allein oder gemeinsam mit anderen &uuml;ber die Zwecke und Mittel der Verarbeitung entscheiden. Zudem informieren wir Sie nachfolgend &uuml;ber die von uns zu Optimierungszwecken sowie zur Steigerung der Nutzungsqualit&auml;t eingesetzten Fremdkomponenten, soweit hierdurch Dritte Daten in wiederum eigener Verantwortung verarbeiten.</p>
  <p>Unsere Datenschutzerkl&auml;rung ist wie folgt gegliedert:</p>
  <p>I. Informationen &uuml;ber uns als Verantwortliche<br>II. Rechte der Nutzer und Betroffenen<br>III. Informationen zur Datenverarbeitung</p>


  <mat-divider></mat-divider>

  <section>
    <h3>I. Informationen &uuml;ber uns als Verantwortliche</h3>
    <p>Verantwortlicher Anbieter und Datenschutzbeauftragter dieses Internetauftritts im datenschutzrechtlichen Sinne ist:</p>
    <p>{{owner}}<br>{{street}}<br>{{city}}<br />Germany</p>
    <p>Tel {{phn}}<br>Mail <a href="{{mlurl}}" class="contact"><code>{{mllink}}</code></a></p>
  </section>

  <mat-divider></mat-divider>

  <section>
    <h3>II. Rechte der Nutzer und Betroffenen</h3>
    <p>Mit Blick auf die nachfolgend noch n&auml;her beschriebene Datenverarbeitung haben die Nutzer und Betroffenen das Recht..</p>
    <ul>
      <li>.. auf Best&auml;tigung, ob sie betreffende Daten verarbeitet werden, auf Auskunft &uuml;ber die verarbeiteten Daten, auf weitere Informationen &uuml;ber die Datenverarbeitung sowie auf Kopien der Daten (vgl. auch Art. 15 DSGVO);</li>
      <li>.. auf Berichtigung oder Vervollst&auml;ndigung unrichtiger bzw. unvollst&auml;ndiger Daten (vgl. auch Art. 16 DSGVO);</li>
      <li>.. auf unverz&uuml;gliche L&ouml;schung der sie betreffenden Daten (vgl. auch Art. 17 DSGVO), oder, alternativ, soweit eine weitere Verarbeitung gem&auml;ß Art. 17 Abs. 3 DSGVO erforderlich ist, auf Einschr&auml;nkung der Verarbeitung nach Maßgabe von Art. 18 DSGVO;</li>
      <li>.. auf Erhalt der sie betreffenden und von ihnen bereitgestellten Daten und auf &uuml;bermittlung dieser Daten an andere Anbieter/Verantwortliche (vgl. auch Art. 20 DSGVO);</li>
      <li>.. auf Beschwerde gegen&uuml;ber der Aufsichtsbeh&ouml;rde, sofern sie der Ansicht sind, dass die sie betreffenden Daten durch den Anbieter unter Verstoß gegen datenschutzrechtliche Bestimmungen verarbeitet werden (vgl. auch Art. 77 DSGVO).</li>
    </ul>
    <p>Dar&uuml;ber hinaus ist der Anbieter dazu verpflichtet, alle Empf&auml;nger, denen gegen&uuml;ber Daten durch den Anbieter offengelegt worden sind, &uuml;ber jedwede Berichtigung oder L&ouml;schung von Daten oder die Einschr&auml;nkung der Verarbeitung, die aufgrund der Artikel 16, 17 Abs. 1, 18 DSGVO erfolgt, zu unterrichten. Diese Verpflichtung besteht jedoch nicht, soweit diese Mitteilung unm&ouml;glich oder mit einem unverh&auml;ltnism&auml;ßigen Aufwand verbunden ist. Unbeschadet dessen hat der Nutzer ein Recht auf Auskunft &uuml;ber diese Empf&auml;nger.</p>
    <p>Ebenfalls haben die Nutzer und Betroffenen nach Art. 21 DSGVO das Recht auf Widerspruch gegen die k&uuml;nftige Verarbeitung der sie betreffenden Daten, sofern die Daten durch den Anbieter nach Maßgabe von Art. 6 Abs. 1 lit. f) DSGVO verarbeitet werden. Insbesondere ist ein Widerspruch gegen die Datenverarbeitung zum Zwecke der Direktwerbung statthaft.</p>
  </section>

  <mat-divider></mat-divider>

  <section>
    <h3>III. Informationen zur Datenverarbeitung</h3>
    <p>Ihre bei Nutzung unseres Internetauftritts verarbeiteten Daten werden gel&ouml;scht oder gesperrt, sobald der Zweck der Speicherung entf&auml;llt, der L&ouml;schung der Daten keine gesetzlichen Aufbewahrungspflichten entgegenstehen und nachfolgend keine anderslautenden Angaben zu einzelnen Verarbeitungsverfahren gemacht werden.</p>

    <h4>Serverdaten</h4>
    <p>Aus technischen Gr&uuml;nden, insbesondere zur Gew&auml;hrleistung eines sicheren und stabilen Internetauftritts, werden Daten durch Ihren Internet-Browser an uns bzw. an unseren Webspace-Provider &uuml;bermittelt. Mit diesen sog. Server-Logfiles werden u.a. Typ und Version Ihres Internetbrowsers, das Betriebssystem, die Website, von der aus Sie auf unseren Internetauftritt gewechselt haben (Referrer URL), die Website(s) unseres Internetauftritts, die Sie besuchen, Datum und Uhrzeit des jeweiligen Zugriffs sowie die IP-Adresse des Internetanschlusses, von dem aus die Nutzung unseres Internetauftritts erfolgt, erhoben.</p>
    <p>Diese so erhobenen Daten werden vorr&uuml;bergehend gespeichert, dies jedoch nicht gemeinsam mit anderen Daten von Ihnen.</p>
    <p>Diese Speicherung erfolgt auf der Rechtsgrundlage von Art. 6 Abs. 1 lit. f) DSGVO. Unser berechtigtes Interesse liegt in der Verbesserung, Stabilit&auml;t, Funktionalit&auml;t und Sicherheit unseres Internetauftritts.</p>
    <p>Die Daten werden sp&auml;testens nach sieben Tage wieder gel&ouml;scht, soweit keine weitere Aufbewahrung zu Beweiszwecken erforderlich ist. Andernfalls sind die Daten bis zur endg&uuml;ltigen Kl&auml;rung eines Vorfalls ganz oder teilweise von der L&ouml;schung ausgenommen.</p>

    <!--
    <h4>Cookies</h4>
    <h5>a) Sitzungs-Cookies/Session-Cookies</h5>
    <p>Wir verwenden mit unserem Internetauftritt sog. Cookies. Cookies sind kleine Textdateien oder andere Speichertechnologien, die durch den von Ihnen eingesetzten Internet-Browser auf Ihrem Endger&auml;t ablegt und gespeichert werden. Durch diese Cookies werden im individuellen Umfang bestimmte Informationen von Ihnen, wie beispielsweise Ihre Browser- oder Standortdaten oder Ihre IP-Adresse, verarbeitet. &nbsp;</p>
    <p>Durch diese Verarbeitung wird unser Internetauftritt benutzerfreundlicher, effektiver und sicherer, da die Verarbeitung bspw. die Wiedergabe unseres Internetauftritts in unterschiedlichen Sprachen oder das Angebot einer Warenkorbfunktion erm&ouml;glicht.</p>
    <p>Rechtsgrundlage dieser Verarbeitung ist Art. 6 Abs. 1 lit b.) DSGVO, sofern diese Cookies Daten zur Vertragsanbahnung oder Vertragsabwicklung verarbeitet werden.</p>
    <p>Falls die Verarbeitung nicht der Vertragsanbahnung oder Vertragsabwicklung dient, liegt unser berechtigtes Interesse in der Verbesserung der Funktionalit&auml;t unseres Internetauftritts. Rechtsgrundlage ist in dann Art. 6 Abs. 1 lit. f) DSGVO.</p>
    <p>Mit Schließen Ihres Internet-Browsers werden diese Session-Cookies gel&ouml;scht.</p>
    <h5>b) Drittanbieter-Cookies</h5>
    <p>Gegebenenfalls werden mit unserem Internetauftritt auch Cookies von Partnerunternehmen, mit denen wir zum Zwecke der Werbung, der Analyse oder der Funktionalit&auml;ten unseres Internetauftritts zusammenarbeiten, verwendet.</p>
    <p>Die Einzelheiten hierzu, insbesondere zu den Zwecken und den Rechtsgrundlagen der Verarbeitung solcher Drittanbieter-Cookies, entnehmen Sie bitte den nachfolgenden Informationen.</p>
    <h5>c) Beseitigungsm&ouml;glichkeit</h5>
    <p>Sie k&ouml;nnen die Installation der Cookies durch eine Einstellung Ihres Internet-Browsers verhindern oder einschr&auml;nken. Ebenfalls k&ouml;nnen Sie bereits gespeicherte Cookies jederzeit l&ouml;schen. Die hierf&uuml;r erforderlichen Schritte und Maßnahmen h&auml;ngen jedoch von Ihrem konkret genutzten Internet-Browser ab. Bei Fragen benutzen Sie daher bitte die Hilfefunktion oder Dokumentation Ihres Internet-Browsers oder wenden sich an dessen Hersteller bzw. Support. Bei sog. Flash-Cookies kann die Verarbeitung allerdings nicht &uuml;ber die Einstellungen des Browsers unterbunden werden. Stattdessen m&uuml;ssen Sie insoweit die Einstellung Ihres Flash-Players &auml;ndern. Auch die hierf&uuml;r erforderlichen Schritte und Maßnahmen h&auml;ngen von Ihrem konkret genutzten Flash-Player ab. Bei Fragen benutzen Sie daher bitte ebenso die Hilfefunktion oder Dokumentation Ihres Flash-Players oder wenden sich an den Hersteller bzw. Benutzer-Support.</p>
    <p>Sollten Sie die Installation der Cookies verhindern oder einschr&auml;nken, kann dies allerdings dazu f&uuml;hren, dass nicht s&auml;mtliche Funktionen unseres Internetauftritts vollumf&auml;nglich nutzbar sind. </p>
    -->
  </section>

  <mat-divider></mat-divider>

  <section>
    <h3></h3>
    <p>
      Diese Datenschutzerkl&auml;rung basiert auf der Muster-Datenschutzerkl&auml;rung der
      <a href="https://www.ratgeberrecht.eu/" target="_blank">Anwaltskanzlei Wei&szlig; & Partner</a>.
    </p>
  </section>
  <!--
  <mat-divider></mat-divider>

  <section>
    <h3 id="applications">Datensammlung in unseren Anwendungen</h3>
    <p>
      Zu Forschungszwecken im Bereich Mensch-Maschine Interaktion sammeln und speichern wir in unserer Web-Anwendung auf hce.chapek9.org Interaktionsdaten.
      <br />Das beinhaltet beispielsweise Mausbewegungen und Clicks. Diese Datensammlung erfolgt anonymisiert. Es werden keine pers&ouml;nlichen, identit&auml;tsbezogenen Daten gespeichert.
      <br />
    </p>
  </section>
  -->

</div>
